In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep
from random import randint

In [2]:
from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings

disable_warnings(InsecureRequestWarning)

page = requests.get('https://www.idescat.cat', verify=False)

List of urls for scraping

In [3]:
url_2021 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=202100"
url_2020 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=202000"
url_2019 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201900"
url_2018 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201800"
url_2017 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201700"
url_2016 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201600"
url_2015 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201500"
url_2014 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201400"
url_2013 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201300"
url_2012 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201200"
url_2011 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201100"
url_2010 = "https://www.idescat.cat/indicadors/?id=aec&n=15786&t=201000"

Checking the response status for the url_2021

In [4]:
response = requests.get(url_2021)
response.status_code

200

Printing the content of the url.

In [5]:
soup = BeautifulSoup(response.text, "html.parser")
soup

<!DOCTYPE html>

<!--[if lt IE 7]><html class="lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]><html class="lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="ca"> <!--<![endif]-->
<head>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta charset="utf-8"/>
<!--[if lt IE 9]>
	<script src="/commonScripts/ext/html5shiv.min.js"></script>
	<![endif]-->
<title>Idescat. Anuari estadístic de Catalunya. Federacions esportives. Clubs i llicències. . 2021</title>
<link href="/estils/std.css" media="all" rel="stylesheet" type="text/css"/>
<link href="/estils/cerca.css" media="all" rel="stylesheet" type="text/css"/>
<link href="/xml/opensearch-ca.xml" rel="search" title="Idescat" type="application/opensearchdescription+xml"/>
<link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/favicon192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/images/favicon180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/images/favicon152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/images/favicon120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/novetats/?m=rss" rel="alternate" title="Idescat. Novetats" type="application/rss+xml"/>
<script src="/commonScripts/idescat.js" type="text/javascript"></script>
<script src="/commonScripts/cat/idescat.js" type="text/javascript"></script>
<link href="//api.idescat.cat/embed/v1/oembed.json?url=https%3A%2F%2Fwww.idescat.cat%2Findicadors%2F%3Fid%3Daec%26n%3D15786%26t%3D202100" rel="alternate" type="application/json+oembed"/>
<link href="//api.idescat.cat/embed/v1/oembed.xml?url=https%3A%2F%2Fwww.idescat.cat%2Findicadors%2F%3Fid%3Daec%26n%3D15786%26t%3D202100" rel="alternate" type="application/xml+oembed"/>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0Z6NJ7PL6K"></script>
<script>IDESCAT.analitica({
"seccio": "dades",
"tema": "cultu",
"estad": "eesp",
"prod": "indic - aec"
});</script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NH8MVLN" style="display:none;visibility:hidden" title="Google Tag Manager" width="0"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="Contingut">
<a class="WAIocult" href="#Titol">Saltar al contingut principal</a>
<header class="ca">
<div class="aplec">
<div id="principal">
<div id="logo"><a href="/" title="Institut d’Estadística de Catalunya (Idescat)">idescat</a></div>
<div aria-label="Idioma de la pàgina" class="idiomes" role="navigation">
<ul><li><a href="?id=aec&amp;n=15786&amp;t=202100&amp;lang=es" hreflang="es" title="Esta página está traducida total o parcialmente al castellano">es</a></li><li><a href="?id=aec&amp;n=15786&amp;t=202100&amp;lang=en" hreflang="en" title="This page is totally or partially translated into English">en</a></li></ul>
</div>
<div id="logogencat">
<a href="http://web.gencat.cat/ca/inici/" title="Generalitat de Catalunya">gencat</a>
</div>
</div>
<div id="org">
<a href="/">Institut d’Estadística de Catalunya</a>
</div>
<nav>
<ul>
<li class="active" id="dades">
<h2><a aria-controls="ARIAnavdades" aria-expanded="false" aria-haspopup="true" href="/dades/">Dades</a></h2>
<div class="tab" id="ARIAnavdades">
<div class="aplec">
<div class="grup">
<h3>Demografia i societat</h3>
<ul>
<li><a href="/tema/xifpo">Població</a></li>
<li><a href="/tema/cultu">Cultura · Llengua</a></li>
<li><a href="/tema/educa">Educació</a></li>
<li><a href="/tema/elecc">Eleccions</a></li>
<li><a href="/tema/justi">Justícia · Seguretat</a></li>
<li><a href="/tema/salut">Salut</a></li>
<li><a href="/tema/treba">Treball</a></li>
</ul>
<h3>Qualitat de vida</h3>
<ul>
<li><a href="/tema/cvida">Condicions de vida</a></li>
<li><a href="/tema/habit">Habitatges i edificis</a></li>
<li><a href="/tema/ingre">Ingressos i consum de les llars</a></li>
<li><a href="/tema/proso">Protecció social</a></li>
</ul>
</div>
<div class="grup">
<h3>Economia</h3>
<ul>
<li><a href="/tema/macro">Macromagnituds</a></li>
<li><a href="/tema/empre">Empreses · Finances</a></li>
<li><a href="/tema/finan">Finances públiques</a></li>
<li><a href="/tema/inver">Inversió i comerç exterior</a></li>
<li><a href="/tema/preus">Preus</a></li>
<li><a href="/tema/recer">Recerca · Tecnologia</a></li>
</ul>
<h3>Sectors econòmics</h3>
<ul>
<li><a href="/tema/agrar">Agricultura · Ramaderia · Pesca</a></li>
<li><a href="/tema/comer">Comerç · Serveis</a></li>
<li><a href="/tema/const">Construcció</a></li>
<li><a href="/tema/indus">Indústria · Energia</a></li>
<li><a href="/tema/trans">Transport</a></li>
<li><a href="/tema/turis">Turisme</a></li>
</ul>
<h3>Medi ambient · Territori</h3>
<ul>
<li><a href="/tema/media">Medi ambient</a></li>
<li><a href="/tema/terri">Territori</a></li>
</ul>
</div>
<div class="grup">
<h3>Temes transversals</h3>
<ul>
<li><a href="/estad/iig">Índex d'igualtat de gènere</a></li>
<li><a href="/dades/ods/">Objectius de desenvolupament sostenible</a></li>
<li><a href="/dades/covid19/">Informació estadística per al seguiment de l'impacte de la covid-19</a></li>
</ul>
<h3>Per àmbit geogràfic</h3>
<ul>
<li><a href="/estad/?geo=prov">Províncies</a></li>
<li><a href="/estad/?geo=at">Àmbits del Pla territorial</a></li>
<li><a href="/estad/?geo=mt">Marques turístiques</a></li>
<li><a href="/estad/?geo=com">Comarques i Aran</a></li>
<li><a href="/estad/?geo=mun">Municipis</a></li>
<li><a href="/estad/?geo=ac">Agrupacions censals</a></li>
<li><a href="/estad/?geo=ep">Entitats de població</a></li>
<li><a href="/estad/?geo=dis">Districtes</a></li>
<li><a href="/estad/?geo=sec">Seccions censals</a></li>
</ul>
<h3>Dades bàsiques</h3>
<ul>
<li><a href="/indicadors/?id=conj">Indicadors de conjuntura econòmica</a></li>
<li><a href="/indicadors/?id=anuals">Indicadors anuals</a></li>
<li><a href="/indicadors/?id=ue">Indicadors de la Unió Europea</a></li>
<li><a href="/pub/?id=inddt">Indicadors demogràfics i de territori</a></li>
<li><a href="/indicadors/?id=aec">Anuari estadístic de Catalunya</a></li>
<li><a href="/emex/">El municipi en xifres</a></li>
</ul>
</div>
<div class="peu"><a href="/estad/">Estadístiques A–Z</a> <strong>•</strong> <a href="/cal/">Calendari</a> <strong>•</strong> <a href="/novetats/">Novetats</a> <strong>•</strong> <a href="/dades/encurs/">Enquestes en curs</a> <strong>•</strong> <a href="/dades/obertes/">Dades obertes</a> <strong>•</strong> <a href="/rectificacions/">Rectificacions</a></div>
</div>
</div>
</li>
<li id="serveis">
<h2><a aria-controls="ARIAnavserveis" aria-expanded="false" aria-haspopup="true" href="/serveis/">Serveis</a></h2>
<div class="tab" id="ARIAnavserveis">
<div class="aplec">
<div class="grup">
<h3>Informació estadística</h3>
<ul>
<li><a href="/serveis/consultes/">Consultes</a></li>
<li><a href="/serveis/certificats/">Certificats</a></li>
<li><a href="//biblio.idescat.cat/cgi-bin/koha/opac-changelanguage.pl?language=ca-ES">Biblioteca</a></li>
<li><a href="//biblio.idescat.cat/publicacions/?l=ca">Publicacions</a></li>
<li><a href="/serveis/suggeriments/">Suggeriments</a></li>
<li class="abanda"><a href="/serveis/carta/">Carta de serveis</a></li>
</ul>
</div>
<div class="grup">
<h3>Per als mitjans de comunicació</h3>
<ul>
<li><a href="/serveis/premsa/">Notes de premsa i consultes</a></li>
</ul>
<h3>Per al sector educatiu</h3>
<ul>
<li><a href="/serveis/educacio/visites/">Visites a l'Idescat</a></li>
<li><a href="/serveis/educacio/sessions/">Sessions monogràfiques</a></li>
<li><a href="/serveis/educacio/concursos/">Concursos</a></li>
</ul>
<h3>Per a investigadors</h3>
<ul>
<li><a href="/serveis/dades/">Dades confidencials</a></li>
</ul>
<h3>Per a desenvolupadors</h3>
<ul>
<li><a href="/dev/api/">API</a></li>
<li><a href="/dev/visual/">Visual</a></li>
</ul>
</div>
<div class="grup">
<h3>Per al Sistema estadístic de Catalunya</h3>
<ul>
<li><a href="/formacio/">Formació i activitats</a></li>
</ul>
<h3>Generals</h3>
<ul>
<li><a href="/serveis/lloguer/">Lloguer d'espais</a></li>
<li><a href="/pagaments/">Pagaments</a></li>
</ul>
</div>
</div>
</div>
</li>
<li id="metodes">
<h2><a aria-controls="ARIAnavmetodes" aria-expanded="false" aria-haspopup="true" href="/metodes/">Mètodes</a></h2>
<div class="tab" id="ARIAnavmetodes">
<div class="aplec">
<div class="grup">
<h3>Classificacions i codis</h3>
<ul>
<li><a href="/metodes/classificacions/">Classificacions estadístiques</a></li>
<li><a href="/codis/">Codis territorials i d'entitats</a></li>
</ul>
</div>
<div class="grup">
<h3>Instruments de qualitat</h3>
<ul>
<li><a href="/cal/">Calendari de difusió de resultats</a></li>
<li><a href="/metodes/difusio/">Política de difusió de resultats</a></li>
<li><a href="/dades/encurs/">Enquestes en curs</a></li>
<li><a href="/rectificacions/">Rectificacions</a></li>
<li><a href="/metodes/bonespractiques/">Codi de bones pràctiques</a></li>
<li><a href="/metodes/siie/">SIIE: Plataforma Cerdà i Qualitas</a></li>
<li><a href="/serveis/carta/">Carta de serveis</a></li>
</ul>
</div>
<div class="grup">
<h3>Recerca i innovació</h3>
<ul>
<li><a href="/sort/">Journal SORT</a></li>
<li><a href="/metodes/manifestdades/">Manifest de les dades</a></li>
</ul>
</div>
</div>
</div>
</li>
<li id="institut">
<h2><a aria-controls="ARIAnavinstitut" aria-expanded="false" aria-haspopup="true" href="/institut/">L'Institut</a></h2>
<div class="tab" id="ARIAnavinstitut">
<div class="aplec">
<div class="grup">
<h3>L'Institut d'Estadística de Catalunya (Idescat)</h3>
<ul>
<li><a href="/institut/idescat/">Presentació</a></li>
<li><a href="/institut/idescat/organitzacio/">Organització</a></li>
<li><a href="/institut/idescat/memoria/">Memòria anual</a></li>
<li><a href="/institut/idescat/convenis/">Convenis</a></li>
<li><a href="/institut/web/privadesa/">Protecció de dades</a></li>
<li><a href="/institut/idescat/transparencia/">Transparència</a></li>
<li><a href="/institut/idescat/contractacio/">Perfil del contractant</a></li>
<li><a href="/institut/idescat/ofertes/">Ofertes de treball</a></li>
<li class="abanda"><a href="/institut/idescat/contacte/">Contacte</a></li>
</ul>
</div>
<div class="grup">
<h3>El Sistema estadístic de Catalunya (SEC)</h3>
<ul>
<li><a href="/institut/sec/">Presentació</a></li>
<li><a href="/institut/sec/crsec/">Consell Rector</a></li>
<li><a href="/institut/sec/legislacio/">Legislació</a></li>
<li><a href="/pec/">Pla estadístic de Catalunya</a></li>
<li><a href="/institut/sec/ciutadans/">Els ciutadans i l'estadística oficial</a></li>
<li><a href="/institut/sec/rfe/">Registre de fitxers estadístics</a></li>
<li><a href="/institut/sec/extranet/">Extranet del SEC</a></li>
</ul>
</div>
</div>
</div>
</li>
<li id="cercador">
<form accept-charset="UTF-8" action="/cercador/" method="get" role="search">
<label class="WAIocult" for="inputSearch">Cercar</label><input accesskey="T" aria-label="Cercar" id="inputSearch" name="q" spellcheck="false" type="search" value=""/>
</form>
</li>
</ul>
</nav>
</div>
</header>
<main>
<div id="Titular">
<div class="aplec">
<ul id="BarraSituacio"><li><a href="?id=aec">Anuari estadístic de Catalunya</a></li><li><a href="?id=aec&amp;n=15173">Demografia · Societat</a></li><li><a href="?id=aec&amp;n=15005">Cultura · Llengua</a></li><li><a href="?id=aec&amp;n=15043">Esports</a></li></ul>
<div id="TitolComp"> <h1 id="Titol"> Federacions esportives. Clubs i llicències</h1>
<div class="Despl">
<form action="." method="get">
<input name="id" type="hidden" value="aec"/>
<input name="n" type="hidden" value="15786"/>
<select aria-label="Període" name="t" size="1">
<option selected="selected" value="202100">2021</option>
<option value="202000">2020</option>
<option value="201900">2019</option>
<option value="201800">2018</option>
<option value="201700">2017</option>
<option value="201600">2016</option>
<option value="201500">2015</option>
<option value="201400">2014</option>
<option value="201300">2013</option>
<option value="201200">2012</option>
<option value="201100">2011</option>
<option value="201000">2010</option>
<option value="200900">2009</option>
<option value="200800">2008</option>
<option value="200700">2007</option>
<option value="200600">2006</option>
<option value="200500">2005</option>
<option value="200400">2004</option>
<option value="200300">2003</option>
<option value="200200">2002</option>
<option value="200100">2001</option>
<option value="200000">2000</option>
</select><button type="submit"><img alt="acceptar" src="/images/confirmar.png" title="acceptar"/></button></form>
</div>
</div>
<ul id="Opcions"><li><a href="/indicadors/?id=aec&amp;n=15786&amp;t=202100&amp;fil=1">Sèrie temporal </a></li><li class="download"><a href="/indicadors/?id=aec&amp;n=15786&amp;t=202100&amp;f=ssv">Descarregar</a></li></ul>
</div>
</div>
<div class="aplec">
<table class="ApartNum xs Cols5">
<caption>
<span class="grup">Federacions esportives. Clubs i llicències</span>
<span class="grup">Catalunya. 2021</span>
</caption>
<colgroup span="1"></colgroup><colgroup span="1"></colgroup><colgroup span="3"></colgroup><thead>
<tr>
<th></th>
<th scope="col"></th>
<th class="cap" colspan="3" scope="colgroup">Llicències</th>
</tr>
<tr class="cap">
<th class="etieti" scope="col"></th>
<th scope="col">Clubs</th>
<th scope="col">Homes</th>
<th scope="col">Dones</th>
<th scope="col">Total</th>
</tr>
</thead>
<tbody>
<tr class="primera total">
<th scope="row">Total</th>
<td data-title="Clubs">8.595</td>
<td data-title="Llicències. Homes">434.198</td>
<td data-title="Llicències. Dones">163.076</td>
<td data-title="Llicències. Total">597.274</td>
</tr>
<tr>
<th scope="row">Activitats subaquàtiques</th>
<td data-title="Clubs">94</td>
<td data-title="Llicències. Homes">3.638</td>
<td data-title="Llicències. Dones">926</td>
<td data-title="Llicències. Total">4.564</td>
</tr>
<tr>
<th scope="row">Aèria</th>
<td data-title="Clubs">74</td>
<td data-title="Llicències. Homes">2.066</td>
<td data-title="Llicències. Dones">96</td>
<td data-title="Llicències. Total">2.162</td>
</tr>
<tr>
<th scope="row">Agility</th>
<td data-title="Clubs">17</td>
<td data-title="Llicències. Homes">141</td>
<td data-title="Llicències. Dones">140</td>
<td data-title="Llicències. Total">281</td>
</tr>
<tr>
<th scope="row">Atletisme</th>
<td data-title="Clubs">129</td>
<td data-title="Llicències. Homes">7.480</td>
<td data-title="Llicències. Dones">6.195</td>
<td data-title="Llicències. Total">13.675</td>
</tr>
<tr>
<th scope="row">Automobilisme</th>
<td data-title="Clubs">197</td>
<td data-title="Llicències. Homes">2.901</td>
<td data-title="Llicències. Dones">358</td>
<td data-title="Llicències. Total">3.259</td>
</tr>
<tr>
<th scope="row">Bàdminton</th>
<td data-title="Clubs">24</td>
<td data-title="Llicències. Homes">325</td>
<td data-title="Llicències. Dones">205</td>
<td data-title="Llicències. Total">530</td>
</tr>
<tr>
<th scope="row">Balls esportius</th>
<td data-title="Clubs">42</td>
<td data-title="Llicències. Homes">320</td>
<td data-title="Llicències. Dones">1.056</td>
<td data-title="Llicències. Total">1.376</td>
</tr>
<tr>
<th scope="row">Basquetbol</th>
<td data-title="Clubs">421</td>
<td data-title="Llicències. Homes">36.389</td>
<td data-title="Llicències. Dones">22.115</td>
<td data-title="Llicències. Total">58.504</td>
</tr>
<tr>
<th scope="row">Beisbol i softbol</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">1.210</td>
<td data-title="Llicències. Dones">276</td>
<td data-title="Llicències. Total">1.486</td>
</tr>
<tr>
<th scope="row">Billar</th>
<td data-title="Clubs">35</td>
<td data-title="Llicències. Homes">1.010</td>
<td data-title="Llicències. Dones">5</td>
<td data-title="Llicències. Total">1.015</td>
</tr>
<tr>
<th scope="row">Bitlles i bowling</th>
<td data-title="Clubs">77</td>
<td data-title="Llicències. Homes">964</td>
<td data-title="Llicències. Dones">231</td>
<td data-title="Llicències. Total">1.195</td>
</tr>
<tr>
<th scope="row">Boxa amateur</th>
<td data-title="Clubs">66</td>
<td data-title="Llicències. Homes">328</td>
<td data-title="Llicències. Dones">72</td>
<td data-title="Llicències. Total">400</td>
</tr>
<tr>
<th scope="row">Caça</th>
<td data-title="Clubs">859</td>
<td data-title="Llicències. Homes">33.455</td>
<td data-title="Llicències. Dones">369</td>
<td data-title="Llicències. Total">33.824</td>
</tr>
<tr>
<th scope="row">Cecs i deficients visuals</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">234</td>
<td data-title="Llicències. Dones">117</td>
<td data-title="Llicències. Total">351</td>
</tr>
<tr>
<th scope="row">Ciclisme</th>
<td data-title="Clubs">711</td>
<td data-title="Llicències. Homes">14.202</td>
<td data-title="Llicències. Dones">1.355</td>
<td data-title="Llicències. Total">15.557</td>
</tr>
<tr>
<th scope="row">Coloms esportius</th>
<td data-title="Clubs">45</td>
<td data-title="Llicències. Homes">819</td>
<td data-title="Llicències. Dones">102</td>
<td data-title="Llicències. Total">921</td>
</tr>
<tr>
<th scope="row">Coloms missatgers</th>
<td data-title="Clubs">8</td>
<td data-title="Llicències. Homes">73</td>
<td data-title="Llicències. Dones">4</td>
<td data-title="Llicències. Total">77</td>
</tr>
<tr>
<th scope="row">Cricket</th>
<td data-title="Clubs">:</td>
<td data-title="Llicències. Homes">:</td>
<td data-title="Llicències. Dones">:</td>
<td data-title="Llicències. Total">:</td>
</tr>
<tr>
<th scope="row">Curses d'orientació</th>
<td data-title="Clubs">24</td>
<td data-title="Llicències. Homes">459</td>
<td data-title="Llicències. Dones">333</td>
<td data-title="Llicències. Total">792</td>
</tr>
<tr>
<th scope="row">Dards</th>
<td data-title="Clubs">15</td>
<td data-title="Llicències. Homes">217</td>
<td data-title="Llicències. Dones">37</td>
<td data-title="Llicències. Total">254</td>
</tr>
<tr>
<th scope="row">Discapacitat física</th>
<td data-title="Clubs">29</td>
<td data-title="Llicències. Homes">378</td>
<td data-title="Llicències. Dones">173</td>
<td data-title="Llicències. Total">551</td>
</tr>
<tr>
<th scope="row">Discapacitat intel·letcual</th>
<td data-title="Clubs">73</td>
<td data-title="Llicències. Homes">803</td>
<td data-title="Llicències. Dones">592</td>
<td data-title="Llicències. Total">1.395</td>
</tr>
<tr>
<th scope="row">Entitats excursionistes</th>
<td data-title="Clubs">429</td>
<td data-title="Llicències. Homes">26.512</td>
<td data-title="Llicències. Dones">15.577</td>
<td data-title="Llicències. Total">42.089</td>
</tr>
<tr>
<th scope="row">Escacs</th>
<td data-title="Clubs">204</td>
<td data-title="Llicències. Homes">6.125</td>
<td data-title="Llicències. Dones">439</td>
<td data-title="Llicències. Total">6.564</td>
</tr>
<tr>
<th scope="row">Esgrima</th>
<td data-title="Clubs">20</td>
<td data-title="Llicències. Homes">420</td>
<td data-title="Llicències. Dones">139</td>
<td data-title="Llicències. Total">559</td>
</tr>
<tr>
<th scope="row">Espeleologia</th>
<td data-title="Clubs">55</td>
<td data-title="Llicències. Homes">1.088</td>
<td data-title="Llicències. Dones">544</td>
<td data-title="Llicències. Total">1.632</td>
</tr>
<tr>
<th scope="row">Esports d'hivern</th>
<td data-title="Clubs">66</td>
<td data-title="Llicències. Homes">3.974</td>
<td data-title="Llicències. Dones">2.826</td>
<td data-title="Llicències. Total">6.800</td>
</tr>
<tr>
<th scope="row">Esquaix i raquetbol</th>
<td data-title="Clubs">22</td>
<td data-title="Llicències. Homes">254</td>
<td data-title="Llicències. Dones">58</td>
<td data-title="Llicències. Total">312</td>
</tr>
<tr>
<th scope="row">Esquí nàutic</th>
<td data-title="Clubs">12</td>
<td data-title="Llicències. Homes">346</td>
<td data-title="Llicències. Dones">147</td>
<td data-title="Llicències. Total">493</td>
</tr>
<tr>
<th scope="row">Físic-culturisme</th>
<td data-title="Clubs">32</td>
<td data-title="Llicències. Homes">241</td>
<td data-title="Llicències. Dones">190</td>

Printing just the table.

In [6]:
License_table=soup.find('table',class_ = "ApartNum xs Cols5")
License_table

<table class="ApartNum xs Cols5">
<caption>
<span class="grup">Federacions esportives. Clubs i llicències</span>
<span class="grup">Catalunya. 2021</span>
</caption>
<colgroup span="1"></colgroup><colgroup span="1"></colgroup><colgroup span="3"></colgroup><thead>
<tr>
<th></th>
<th scope="col"></th>
<th class="cap" colspan="3" scope="colgroup">Llicències</th>
</tr>
<tr class="cap">
<th class="etieti" scope="col"></th>
<th scope="col">Clubs</th>
<th scope="col">Homes</th>
<th scope="col">Dones</th>
<th scope="col">Total</th>
</tr>
</thead>
<tbody>
<tr class="primera total">
<th scope="row">Total</th>
<td data-title="Clubs">8.595</td>
<td data-title="Llicències. Homes">434.198</td>
<td data-title="Llicències. Dones">163.076</td>
<td data-title="Llicències. Total">597.274</td>
</tr>
<tr>
<th scope="row">Activitats subaquàtiques</th>
<td data-title="Clubs">94</td>
<td data-title="Llicències. Homes">3.638</td>
<td data-title="Llicències. Dones">926</td>
<td data-title="Llicències. Total">4.564</td>
</tr>
<tr>
<th scope="row">Aèria</th>
<td data-title="Clubs">74</td>
<td data-title="Llicències. Homes">2.066</td>
<td data-title="Llicències. Dones">96</td>
<td data-title="Llicències. Total">2.162</td>
</tr>
<tr>
<th scope="row">Agility</th>
<td data-title="Clubs">17</td>
<td data-title="Llicències. Homes">141</td>
<td data-title="Llicències. Dones">140</td>
<td data-title="Llicències. Total">281</td>
</tr>
<tr>
<th scope="row">Atletisme</th>
<td data-title="Clubs">129</td>
<td data-title="Llicències. Homes">7.480</td>
<td data-title="Llicències. Dones">6.195</td>
<td data-title="Llicències. Total">13.675</td>
</tr>
<tr>
<th scope="row">Automobilisme</th>
<td data-title="Clubs">197</td>
<td data-title="Llicències. Homes">2.901</td>
<td data-title="Llicències. Dones">358</td>
<td data-title="Llicències. Total">3.259</td>
</tr>
<tr>
<th scope="row">Bàdminton</th>
<td data-title="Clubs">24</td>
<td data-title="Llicències. Homes">325</td>
<td data-title="Llicències. Dones">205</td>
<td data-title="Llicències. Total">530</td>
</tr>
<tr>
<th scope="row">Balls esportius</th>
<td data-title="Clubs">42</td>
<td data-title="Llicències. Homes">320</td>
<td data-title="Llicències. Dones">1.056</td>
<td data-title="Llicències. Total">1.376</td>
</tr>
<tr>
<th scope="row">Basquetbol</th>
<td data-title="Clubs">421</td>
<td data-title="Llicències. Homes">36.389</td>
<td data-title="Llicències. Dones">22.115</td>
<td data-title="Llicències. Total">58.504</td>
</tr>
<tr>
<th scope="row">Beisbol i softbol</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">1.210</td>
<td data-title="Llicències. Dones">276</td>
<td data-title="Llicències. Total">1.486</td>
</tr>
<tr>
<th scope="row">Billar</th>
<td data-title="Clubs">35</td>
<td data-title="Llicències. Homes">1.010</td>
<td data-title="Llicències. Dones">5</td>
<td data-title="Llicències. Total">1.015</td>
</tr>
<tr>
<th scope="row">Bitlles i bowling</th>
<td data-title="Clubs">77</td>
<td data-title="Llicències. Homes">964</td>
<td data-title="Llicències. Dones">231</td>
<td data-title="Llicències. Total">1.195</td>
</tr>
<tr>
<th scope="row">Boxa amateur</th>
<td data-title="Clubs">66</td>
<td data-title="Llicències. Homes">328</td>
<td data-title="Llicències. Dones">72</td>
<td data-title="Llicències. Total">400</td>
</tr>
<tr>
<th scope="row">Caça</th>
<td data-title="Clubs">859</td>
<td data-title="Llicències. Homes">33.455</td>
<td data-title="Llicències. Dones">369</td>
<td data-title="Llicències. Total">33.824</td>
</tr>
<tr>
<th scope="row">Cecs i deficients visuals</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">234</td>
<td data-title="Llicències. Dones">117</td>
<td data-title="Llicències. Total">351</td>
</tr>
<tr>
<th scope="row">Ciclisme</th>
<td data-title="Clubs">711</td>
<td data-title="Llicències. Homes">14.202</td>
<td data-title="Llicències. Dones">1.355</td>
<td data-title="Llicències. Total">15.557</td>
</tr>
<tr>
<th scope="row">Coloms esportius</th>
<td data-title="Clubs">45</td>
<td data-title="Llicències. Homes">819</td>
<td data-title="Llicències. Dones">102</td>
<td data-title="Llicències. Total">921</td>
</tr>
<tr>
<th scope="row">Coloms missatgers</th>
<td data-title="Clubs">8</td>
<td data-title="Llicències. Homes">73</td>
<td data-title="Llicències. Dones">4</td>
<td data-title="Llicències. Total">77</td>
</tr>
<tr>
<th scope="row">Cricket</th>
<td data-title="Clubs">:</td>
<td data-title="Llicències. Homes">:</td>
<td data-title="Llicències. Dones">:</td>
<td data-title="Llicències. Total">:</td>
</tr>
<tr>
<th scope="row">Curses d'orientació</th>
<td data-title="Clubs">24</td>
<td data-title="Llicències. Homes">459</td>
<td data-title="Llicències. Dones">333</td>
<td data-title="Llicències. Total">792</td>
</tr>
<tr>
<th scope="row">Dards</th>
<td data-title="Clubs">15</td>
<td data-title="Llicències. Homes">217</td>
<td data-title="Llicències. Dones">37</td>
<td data-title="Llicències. Total">254</td>
</tr>
<tr>
<th scope="row">Discapacitat física</th>
<td data-title="Clubs">29</td>
<td data-title="Llicències. Homes">378</td>
<td data-title="Llicències. Dones">173</td>
<td data-title="Llicències. Total">551</td>
</tr>
<tr>
<th scope="row">Discapacitat intel·letcual</th>
<td data-title="Clubs">73</td>
<td data-title="Llicències. Homes">803</td>
<td data-title="Llicències. Dones">592</td>
<td data-title="Llicències. Total">1.395</td>
</tr>
<tr>
<th scope="row">Entitats excursionistes</th>
<td data-title="Clubs">429</td>
<td data-title="Llicències. Homes">26.512</td>
<td data-title="Llicències. Dones">15.577</td>
<td data-title="Llicències. Total">42.089</td>
</tr>
<tr>
<th scope="row">Escacs</th>
<td data-title="Clubs">204</td>
<td data-title="Llicències. Homes">6.125</td>
<td data-title="Llicències. Dones">439</td>
<td data-title="Llicències. Total">6.564</td>
</tr>
<tr>
<th scope="row">Esgrima</th>
<td data-title="Clubs">20</td>
<td data-title="Llicències. Homes">420</td>
<td data-title="Llicències. Dones">139</td>
<td data-title="Llicències. Total">559</td>
</tr>
<tr>
<th scope="row">Espeleologia</th>
<td data-title="Clubs">55</td>
<td data-title="Llicències. Homes">1.088</td>
<td data-title="Llicències. Dones">544</td>
<td data-title="Llicències. Total">1.632</td>
</tr>
<tr>
<th scope="row">Esports d'hivern</th>
<td data-title="Clubs">66</td>
<td data-title="Llicències. Homes">3.974</td>
<td data-title="Llicències. Dones">2.826</td>
<td data-title="Llicències. Total">6.800</td>
</tr>
<tr>
<th scope="row">Esquaix i raquetbol</th>
<td data-title="Clubs">22</td>
<td data-title="Llicències. Homes">254</td>
<td data-title="Llicències. Dones">58</td>
<td data-title="Llicències. Total">312</td>
</tr>
<tr>
<th scope="row">Esquí nàutic</th>
<td data-title="Clubs">12</td>
<td data-title="Llicències. Homes">346</td>
<td data-title="Llicències. Dones">147</td>
<td data-title="Llicències. Total">493</td>
</tr>
<tr>
<th scope="row">Físic-culturisme</th>
<td data-title="Clubs">32</td>
<td data-title="Llicències. Homes">241</td>
<td data-title="Llicències. Dones">190</td>
<td data-title="Llicències. Total">431</td>
</tr>
<tr>
<th scope="row">Futbol</th>
<td data-title="Clubs">1.249</td>
<td data-title="Llicències. Homes">132.705</td>
<td data-title="Llicències. Dones">14.356</td>
<td data-title="Llicències. Total">147.061</td>
</tr>
<tr>
<th scope="row">Futbol americà</th>
<td data-title="Clubs">31</td>
<td data-title="Llicències. Homes">1.474</td>
<td data-title="Llicències. Dones">323</td>
<td data-title="Llicències. Total">1.797</td>
</tr>
<tr>
<th scope="row">Futbol sala</th>
<td data-title="Clubs">85</td>
<td data-title="Llicències. Homes">1.611</td>
<td data-title="Llicències. Dones">243</td>
<td data-title="Llicències. Total">1.854</td>
</tr>
<tr>
<th scope="row">Gimnàstica</th>
<td data-title="Clubs">136</td>
<td data-title="Llicències. Homes">639</td>
<td data-title="Llicències. Dones">5.387</td>
<td data-title="Llicències. Total">6.026</td>
</tr>
<tr>
<th scope="row">Golf</th>
<td data-title="Clubs">50</td>
<td data-title="Llicències. Homes">20.914</td>
<td data-title="Llicències. Dones">7.090</td>
<td data-title="Llicències. Total">28.004</td>
</tr>
<tr>
<th scope="row">Halterofília</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">347</td>
<td data-title="Llicències. Dones">187</td>
<td data-title="Llicències. Total">534</td>
</tr>
<tr>
<th scope="row">Handbol</th>
<td data-title="Clubs">108</td>
<td data-title="Llicències. Homes">7.559</td>
<td data-title="Llicències. Dones">3.817</td>
<td data-title="Llicències. Total">11.376</td>
</tr>
<tr>
<th scope="row">Hípica</th>
<td data-title="Clubs">147</td>
<td data-title="Llicències. Homes">2.512</td>
<td data-title="Llicències. Dones">8.477</td>
<td data-title="Llicències. Total">10.989</td>
</tr>
<tr>
<th scope="row">Hoquei</th>
<td data-title="Clubs">30</td>
<td data-title="Llicències. Homes">4.119</td>
<td data-title="Llicències. Dones">3.599</td>
<td data-title="Llicències. Total">7.718</td>
</tr>
<tr>
<th scope="row">Judo i disciplines associades</th>
<td data-title="Clubs">107</td>
<td data-title="Llicències. Homes">3.067</td>
<td data-title="Llicències. Dones">988</td>
<td data-title="Llicències. Total">4.055</td>
</tr>
<tr>
<th scope="row">Karate</th>
<td data-title="Clubs">150</td>
<td data-title="Llicències. Homes">6.165</td>
<td data-title="Llicències. Dones">2.579</td>
<td data-title="Llicències. Total">8.744</td>
</tr>
<tr>
<th scope="row">Kick-Boxing i Moay-Thaï</th>
<td data-title="Clubs">48</td>
<td data-title="Llicències. Homes">1.178</td>
<td data-title="Llicències. Dones">354</td>
<td data-title="Llicències. Total">1.532</td>
</tr>
<tr>
<th scope="row">Korfbal</th>
<td data-title="Clubs">10</td>
<td data-title="Llicències. Homes">89</td>
<td data-title="Llicències. Dones">85</td>
<td data-title="Llicències. Total">174</td>
</tr>
<tr>
<th scope="row">Lluita</th>
<td data-title="Clubs">11</td>
<td data-title="Llicències. Homes">998</td>
<td data-title="Llicències. Dones">207</td>
<td data-title="Llicències. Total">1.205</td>
</tr>
<tr>
<th scope="row">Motociclisme</th>
<td data-title="Clubs">165</td>
<td data-title="Llicències. Homes">5.729</td>
<td data-title="Llicències. Dones">252</td>
<td data-title="Llicències. Total">5.981</td>
</tr>
<tr>
<th scope="row">Motonàutica</th>
<td data-title="Clubs">30</td>
<td data-title="Llicències. Homes">59</td>
<td data-title="Llicències. Dones">14</td>
<td data-title="Llicències. Total">73</td>
</tr>
<tr>
<th scope="row">Natació</th>
<td data-title="Clubs">126</td>
<td data-title="Llicències. Homes">7.605</td>
<td data-title="Llicències. Dones">6.069</td>
<td data-title="Llicències. Total">13.674</td>
</tr>
<tr>
<th scope="row">Pàdel</th>
<td data-title="Clubs">277</td>
<td data-title="Llicències. Homes">12.724</td>
<td data-title="Llicències. Dones">8.566</td>
<td data-title="Llicències. Total">21.290</td>
</tr>
<tr>
<th scope="row">Paràlisi cerebral</th>
<td data-title="Clubs">73</td>
<td data-title="Llicències. Homes">139</td>
<td data-title="Llicències. Dones">50</td>
<td data-title="Llicències. Total">189</td>
</tr>
<tr>
<th scope="row">Patinatge</th>
<td data-title="Clubs">409</td>
<td data-title="Llicències. Homes">8.894</td>
<td data-title="Llicències. Dones">13.054</td>
<td data-title="Llicències. Total">21.948</td>
</tr>
<tr>
<th scope="row">Pentatló modern</th>
<td data-title="Clubs">9</td>
<td data-title="Llicències. Homes">260</td>
<td data-title="Llicències. Dones">262</td>
<td data-title="Llicències. Total">522</td>
</tr>
<tr>
<th scope="row">Pesca esportiva i casting</th>
<td data-title="Clubs">:</td>
<td data-title="Llicències. Homes">:</td>
<td data-title="Llicències. Dones">:</td>
<td data-title="Llicències. Total">:</td>
</tr>
<tr>
<th scope="row">Petanca</th>
<td data-title="Clubs">292</td>
<td data-title="Llicències. Homes">2.640</td>
<td data-title="Llicències. Dones">661</td>
<td data-title="Llicències. Total">3.301</td>
</tr>
<tr>
<th scope="row">Pilota</th>
<td data-title="Clubs">28</td>
<td data-title="Llicències. Homes">1.843</td>
<td data-title="Llicències. Dones">233</td>
<td data-title="Llicències. Total">2.076</td>
</tr>
<tr>
<th scope="row">Piragüisme</th>
<td data-title="Clubs">17</td>
<td data-title="Llicències. Homes">1.125</td>
<td data-title="Llicències. Dones">441</td>
<td data-title="Llicències. Total">1.566</td>
</tr>
<tr>
<th scope="row">Pitch and putt</th>
<td data-title="Clubs">66</td>
<td data-title="Llicències. Homes">9.078</td>
<td data-title="Llicències. Dones">1.763</td>
<td data-title="Llicències. Total">10.841</td>
</tr>
<tr>
<th scope="row">Polo</th>
<td data-title="Clubs">8</td>
<td data-title="Llicències. Homes">61</td>
<td data-title="Llicències. Dones">15</td>
<td data-title="Llicències. Total">76</td>
</tr>
<tr>
<th scope="row">Rem</th>
<td data-title="Clubs">38</td>
<td data-title="Llicències. Homes">1.529</td>
<td data-title="Llicències. Dones">1.660</td>
<td data-title="Llicències. Total">3.189</td>
</tr>
<tr>
<th scope="row">Rugbi</th>
<td data-title="Clubs">48</td>
<td data-title="Llicències. Homes">4.032</td>
<td data-title="Llicències. Dones">1.496</td>
<td data-title="Llicències. Total">5.528</td>
</tr>
<tr>
<th scope="row">Salvament i socorrisme</th>
<td data-title="Clubs">12</td>
<td data-title="Llicències. Homes">120</td>
<td data-title="Llicències. Dones">129</td>
<td data-title="Llicències. Total">249</td>
</tr>
<tr>
<th scope="row">Sords</th>
<td data-title="Clubs">13</td>
<td data-title="Llicències. Homes">1.148</td>
<td data-title="Llicències. Dones">802</td>
<td data-title="Llicències. Total">1.950</td>
</tr>
<tr>
<th scope="row">Taekwondo</th>
<td data-title="Clubs">160</td>
<td data-title="Llicències. Homes">7.482</td>
<td data-title="Llicències. Dones">3.867</td>
<td data-title="Llicències. Total">11.349</td>
</tr>
<tr>
<th scope="row">Tennis</th>
<td data-title="Clubs">217</td>
<td data-title="Llicències. Homes">13.984</td>
<td data-title="Llicències. Dones">6.958</td>
<td data-title="Llicències. Total">20.942</td>
</tr>
<tr>
<th scope="row">Tennis de taula</th>
<td data-title="Clubs">120</td>
<td data-title="Llicències. Homes">3.499</td>
<td data-title="Llicències. Dones">410</td>
<td data-title="Llicències. Total">3.909</td>
</tr>
<tr>
<th scope="row">Tir amb arc</th>
<td data-title="Clubs">69</td>
<td data-title="Llicències. Homes">2.238</td>
<td data-title="Llicències. Dones">759</td>
<td data-title="Llicències. Total">2.997</td>
</tr>
<tr>
<th scope="row">Tir olímpic</th>
<td data-title="Clubs">61</td>
<td data-title="Llicències. Homes">10.471</td>
<td data-title="Llicències. Dones">803</td>
<td data-title="Llicències. Total">11.274</td>
</tr>
<tr>
<th scope="row">Triatló</th>
<td data-title="Clubs">119</td>
<td data-title="Llicències. Homes">2.383</td>
<td data-title="Llicències. Dones">900</td>
<td data-title="Llicències. Total">3.283</td>
</tr>
<tr>
<th scope="row">Twirling</th>
<td data-title="Clubs">21</td>
<td data-title="Llicències. Homes">70</td>
<td data-title="Llicències. Dones">968</td>
<td data-title="Llicències. Total">1.038</td>
</tr>
<tr>
<th scope="row">Unió de biketrial (1)</th>
<td data-title="Clubs">20</td>
<td data-title="Llicències. Homes">279</td>
<td data-title="Llicències. Dones">12</td>
<td data-title="Llicències. Total">291</td>
</tr>
<tr>
<th scope="row">Vela</th>
<td data-title="Clubs">104</td>
<td data-title="Llicències. Homes">4.936</td>
<td data-title="Llicències. Dones">2.202</td>
<td data-title="Llicències. Total">7.138</td>
</tr>
<tr class="darrera">
<th scope="row">Voleibol</th>
<td data-title="Clubs">118</td>
<td data-title="Llicències. Homes">2.121</td>
<td data-title="Llicències. Dones">8.361</td>
<td data-title="Llicències. Total">10.482</td>
</tr>
</tbody><tfoot>
<tr>
<th colspan="5">Font: Consell Català de l'Esport.</th>
</tr>
<tr>
<th colspan="5">Nota: (1) Les unions de clubs són el pas previ a la creació d'una federació.</th>
</tr>
<tr>
<th colspan="5"></th>
</tr>
</tfoot>
</table>

In [7]:
List_activities = []

for activity in License_table.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities.append(row.find('th').text)
        
        
List_licences=[]

for activity in License_table.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences.append(row.find_all('td')[3].text)

Creating a dataframe

In [8]:
Licenses_2021 = pd.DataFrame({"Sport":List_activities,
                       "Total_licences":List_licences,
                      })

Getting just the value for Ciclism and creating a new column for the year.

In [9]:
Licenses_2021=Licenses_2021[Licenses_2021['Sport']=='Ciclisme']
Licenses_2021['Year'] = ['2021']
Licenses_2021.head()

       Sport Total_licences  Year
15  Ciclisme         15.557  2021

Doing the same process for each url.

In [10]:
response2020 = requests.get(url_2020)
soup2020 = BeautifulSoup(response2020.text, "html.parser")
License_table_2020=soup2020.find('table',class_ = "ApartNum xs Cols5")

In [11]:
List_activities_2020= []

for activity in License_table_2020.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2020.append(row.find('th').text)
        
        
List_licences_2020=[]

for activity in License_table_2020.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2020.append(row.find_all('td')[3].text)

In [12]:
Licenses_2020 = pd.DataFrame({"Sport":List_activities_2020,
                       "Total_licences":List_licences_2020,
                      })

Licenses_2020=Licenses_2020[Licenses_2020['Sport']=='Ciclisme']
Licenses_2020['Year'] = ['2020']
Licenses_2020.head()

       Sport Total_licences  Year
15  Ciclisme         17.168  2020

In [13]:
response2019 = requests.get(url_2019)
soup2019= BeautifulSoup(response2019.text, "html.parser")
License_table_2019=soup2019.find('table',class_ = "ApartNum xs Cols5")


List_activities_2019= []

for activity in License_table_2019.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2019.append(row.find('th').text)
        
        
List_licences_2019=[]

for activity in License_table_2019.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2019.append(row.find_all('td')[3].text)


Licenses_2019 = pd.DataFrame({"Sport":List_activities_2019,
                       "Total_licences":List_licences_2019,
                      })

Licenses_2019=Licenses_2019[Licenses_2019['Sport']=='Ciclisme']
Licenses_2019['Year'] = ['2019']
Licenses_2019.head()

       Sport Total_licences  Year
15  Ciclisme         16.595  2019

In [14]:
response2018 = requests.get(url_2018)
soup2018= BeautifulSoup(response2018.text, "html.parser")
License_table_2018=soup2018.find('table',class_ = "ApartNum xs Cols5")


List_activities_2018= []

for activity in License_table_2018.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2018.append(row.find('th').text)
        
        
List_licences_2018=[]

for activity in License_table_2018.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2018.append(row.find_all('td')[3].text)


Licenses_2018 = pd.DataFrame({"Sport":List_activities_2018,
                       "Total_licences":List_licences_2018,
                      })

Licenses_2018=Licenses_2018[Licenses_2018['Sport']=='Ciclisme']
Licenses_2018['Year'] = ['2018']
Licenses_2018.head()

       Sport Total_licences  Year
15  Ciclisme         16.137  2018

In [15]:
response2017 = requests.get(url_2017)
soup2017= BeautifulSoup(response2017.text, "html.parser")
License_table_2017=soup2017.find('table',class_ = "ApartNum xs Cols5")


List_activities_2017= []

for activity in License_table_2017.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2017.append(row.find('th').text)
        
        
List_licences_2017=[]

for activity in License_table_2017.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2017.append(row.find_all('td')[3].text)


Licenses_2017 = pd.DataFrame({"Sport":List_activities_2017,
                       "Total_licences":List_licences_2017,
                      })

Licenses_2017=Licenses_2017[Licenses_2017['Sport']=='Ciclisme']
Licenses_2017['Year'] = ['2017']
Licenses_2017.head()

       Sport Total_licences  Year
15  Ciclisme         16.544  2017

In [16]:
response2016 = requests.get(url_2016)
soup2016= BeautifulSoup(response2016.text, "html.parser")
License_table_2016=soup2016.find('table',class_ = "ApartNum xs Cols5")


List_activities_2016= []

for activity in License_table_2016.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2016.append(row.find('th').text)
        
        
List_licences_2016=[]

for activity in License_table_2016.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2016.append(row.find_all('td')[3].text)


Licenses_2016 = pd.DataFrame({"Sport":List_activities_2016,
                       "Total_licences":List_licences_2016,
                      })

Licenses_2016=Licenses_2016[Licenses_2016['Sport']=='Ciclisme']
Licenses_2016['Year'] = ['2016']
Licenses_2016.head()

       Sport Total_licences  Year
15  Ciclisme         19.954  2016

In [17]:
response2015 = requests.get(url_2015)
soup2014= BeautifulSoup(response2015.text, "html.parser")
License_table_2015=soup2014.find('table',class_ = "ApartNum xs Cols5")


List_activities_2015= []

for activity in License_table_2015.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2015.append(row.find('th').text)
        
        
List_licences_2015=[]

for activity in License_table_2015.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2015.append(row.find_all('td')[3].text)


Licenses_2015 = pd.DataFrame({"Sport":List_activities_2015,
                       "Total_licences":List_licences_2015,
                      })

Licenses_2015=Licenses_2015[Licenses_2015['Sport']=='Ciclisme']
Licenses_2015['Year'] = ['2015']
Licenses_2015.head()

       Sport Total_licences  Year
14  Ciclisme         19.209  2015

In [18]:
response2014 = requests.get(url_2014)
soup2014= BeautifulSoup(response2014.text, "html.parser")
License_table_2014=soup2014.find('table',class_ = "ApartNum xs Cols5")


List_activities_2014= []

for activity in License_table_2014.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2014.append(row.find('th').text)
        
        
List_licences_2014=[]

for activity in License_table_2014.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2014.append(row.find_all('td')[3].text)


Licenses_2014 = pd.DataFrame({"Sport":List_activities_2014,
                       "Total_licences":List_licences_2014,
                      })

Licenses_2014=Licenses_2014[Licenses_2014['Sport']=='Ciclisme']
Licenses_2014['Year'] = ['2014']
Licenses_2014.head()

       Sport Total_licences  Year
14  Ciclisme         16.853  2014

In [19]:
response2013 = requests.get(url_2013)
soup2013= BeautifulSoup(response2013.text, "html.parser")
License_table_2013=soup2013.find('table',class_ = "ApartNum xs Cols5")


List_activities_2013= []

for activity in License_table_2013.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2013.append(row.find('th').text)
        
        
List_licences_2013=[]

for activity in License_table_2013.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2013.append(row.find_all('td')[3].text)


Licenses_2013 = pd.DataFrame({"Sport":List_activities_2013,
                       "Total_licences":List_licences_2013,
                      })

Licenses_2013=Licenses_2013[Licenses_2013['Sport']=='Ciclisme']
Licenses_2013['Year'] = ['2013']
Licenses_2013.head()

       Sport Total_licences  Year
14  Ciclisme         16.776  2013

In [20]:
response2012 = requests.get(url_2012)
soup2012= BeautifulSoup(response2012.text, "html.parser")
License_table_2012=soup2012.find('table',class_ = "ApartNum xs Cols5")


List_activities_2012= []

for activity in License_table_2012.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2012.append(row.find('th').text)
        
        
List_licences_2012=[]

for activity in License_table_2012.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2012.append(row.find_all('td')[3].text)


Licenses_2012 = pd.DataFrame({"Sport":List_activities_2012,
                       "Total_licences":List_licences_2012,
                      })

Licenses_2012=Licenses_2012[Licenses_2012['Sport']=='Ciclisme']
Licenses_2012['Year'] = ['2012']
Licenses_2012.head()

       Sport Total_licences  Year
14  Ciclisme         15.893  2012

In [21]:
response2011 = requests.get(url_2011)
soup2011= BeautifulSoup(response2011.text, "html.parser")
License_table_2011=soup2011.find('table',class_ = "ApartNum xs Cols5")


List_activities_2011= []

for activity in License_table_2011.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2011.append(row.find('th').text)
        
        
List_licences_2011=[]

for activity in License_table_2011.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2011.append(row.find_all('td')[3].text)


Licenses_2011 = pd.DataFrame({"Sport":List_activities_2011,
                       "Total_licences":List_licences_2011,
                      })

Licenses_2011=Licenses_2011[Licenses_2011['Sport']=='Ciclisme']
Licenses_2011['Year'] = ['2011']
Licenses_2011.head()

       Sport Total_licences  Year
14  Ciclisme         15.473  2011

In [22]:
response2010 = requests.get(url_2010)
soup2010= BeautifulSoup(response2010.text, "html.parser")
License_table_2010=soup2010.find('table',class_ = "ApartNum xs Cols5")


List_activities_2010= []

for activity in License_table_2010.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_activities_2010.append(row.find('th').text)
        
        
List_licences_2010=[]

for activity in License_table_2010.find_all('tbody'):
    rows = activity.find_all('tr')
    for row in rows:
        List_licences_2010.append(row.find_all('td')[3].text)


Licenses_2010 = pd.DataFrame({"Sport":List_activities_2010,
                       "Total_licences":List_licences_2010,
                      })

Licenses_2010=Licenses_2010[Licenses_2010['Sport']=='Ciclisme']
Licenses_2010['Year'] = ['2010']
Licenses_2010.head()

       Sport Total_licences  Year
14  Ciclisme         15.514  2010

Merging all the dataframes

In [23]:
all_licenses =pd.concat( [Licenses_2010, Licenses_2011, Licenses_2012, Licenses_2013, Licenses_2014, Licenses_2015, Licenses_2016, Licenses_2017, Licenses_2018, Licenses_2019, Licenses_2020, Licenses_2021] )
all_licenses.head(20)

       Sport Total_licences  Year
14  Ciclisme         15.514  2010
14  Ciclisme         15.473  2011
14  Ciclisme         15.893  2012
14  Ciclisme         16.776  2013
14  Ciclisme         16.853  2014
14  Ciclisme         19.209  2015
15  Ciclisme         19.954  2016
15  Ciclisme         16.544  2017
15  Ciclisme         16.137  2018
15  Ciclisme         16.595  2019
15  Ciclisme         17.168  2020
15  Ciclisme         15.557  2021

In [24]:
all_licenses=all_licenses.reindex(columns=['Year','Total_licences'])
all_licenses

    Year Total_licences
14  2010         15.514
14  2011         15.473
14  2012         15.893
14  2013         16.776
14  2014         16.853
14  2015         19.209
15  2016         19.954
15  2017         16.544
15  2018         16.137
15  2019         16.595
15  2020         17.168
15  2021         15.557

In [25]:
all_licenses['Total_licences']=all_licenses['Total_licences'].astype(float)
all_licenses.dtypes

Year               object
Total_licences    float64
dtype: object

In [26]:
# saving the cleaned data.
all_licenses.to_csv('all_licenses_merged_final.csv', header=True, index=False)